name: GoLang CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.1

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install static check
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run static check
      run: staticcheck ./...

    - name: Install go lint
      run: go install golang.org/x/lint/golint@latest

    - name: Run go lint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...
